# Tarea 
Calculo de pesos son de importancia de la IA va a adar a los datos(no es una definicion formal).

In [ ]:
import numpy as np

# calculo de pesos:
def calcular_activacion(entradas, pesos, sesgo=0):
    """
    Simula la activación de una neurona.
    Entradas: Vectores(tensor de rango 1)
    pesos: Vectores(misma dimensión que entradas)
    """
    # Producto escalar.
    activacion = np.dot(entradas, pesos) + sesgo
    return activacion


# prueba1
x = np.array([1.5, 2.0, -0.5]) # ejemplo de entradas [ edad, ingresos, historial ]
w = np.array([0.8, 0.1, 0.4]) # importancias de los valores de entrada son los pesos sinapticos
resultado_activacion = calcular_activacion(x, w)
print("Resultado de la activación:", resultado_activacion)






Resultado de la activación: 1.2000000000000002


In [3]:

def reestructurar_datos(matrizA, matrizB):
    """ 
        Dimensiones
    """
    print(f"dimensiones originales Matriz A:{matrizA.shape}")
    print(f"dimensiones originales Matriz A:{matrizB.shape}")
    print(f"matriz A:{matrizA.shape[0]} -•- {matrizA.shape[1]}")
    print(f"matriz B:{matrizB.shape[0]} -•- {matrizB.shape[1]}")
    # Typos de datos
    print(type(matrizA))
    print(type(matrizB.T))
    
    # Trnsposicion Simple
    print(f'matrizB transpuesta ► {matrizB.T}')

    # Validacion de dimensiones para multiplicar
    if( matrizA.shape[1] != matrizB.shape[0]):
        print("Las dimensiones no son compatibles para multiplicar.")
    else:
        print (f'DIMENSIONES RESULTADO: {np.matmul(matrizA, matrizB)}')
    
# Transposicion de datos:
# requisito: numero de columnas coincida con el numero de filas de las matrices a multiplicar.
A = np.array([[1, 2], [1, 4]])
B = np.array([[5, 6], [7, 8]])

reestructurar_datos(A, B)




dimensiones originales Matriz A:(2, 2)
dimensiones originales Matriz A:(2, 2)
matriz A:2 -•- 2
matriz B:2 -•- 2
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
matrizB transpuesta ► [[5 7]
 [6 8]]
DIMENSIONES RESULTADO: [[19 22]
 [33 38]]


In [2]:
import numpy as np
def resolver_sistema_lineal(A, B):
    """
        Resuelve un sistema de ecuaciones lineales Ax = B
    """
    print(f'• A)\n {A}')
    print(f'• B) \n{B}')
    try:
        # Calculo de la inversa de A
        a = np.linalg.inv(A)
        # print(f'\n• inversa \n{inversa}')

        # Calculo del producto matricial
        b = np.dot( A, B )

        # Producto Matricial
        c = A.dot(B)

        # Transponer una matriz
        d = A.T

        return a, b, c , d
    except np.linalg.LinAlgError as e:
        print (f"Error al resolver el sistema: {e}")
        return None , None

"""
"""
A = np.array([[1, 1, 1], [1, 2, 1], [1, 3, 2]])
B = np.array([-1, -2, 3])

a, b, c, d = resolver_sistema_lineal(A, B)
print("\n■ Solucion")
print(f'\n• inversa: \n{a}')
print(f'\n• producto matricial 1:\n{b}')
print(f'\n• producto matricial 2:\n{c}')
print(f'\n• Transpuesta de A:\n{d}')

• A)
 [[1 1 1]
 [1 2 1]
 [1 3 2]]
• B) 
[-1 -2  3]

■ Solucion

• inversa: 
[[ 1.  1. -1.]
 [-1.  1.  0.]
 [ 1. -2.  1.]]

• producto matricial 1:
[ 0 -2 -1]

• producto matricial 2:
[ 0 -2 -1]

• Transpuesta de A:
[[1 1 1]
 [1 2 3]
 [1 1 2]]
